security:
  basic:
    userPassMap:
      ratpack: 588a0b51a7bdc335a74d8afa902a77db0dac2281ebad3f5
postgres:
  user: henninb
  password: monday1
  portNumber: 5432
  databaseName: finance_db
  serverName: 192.168.100.124