#addons:
#  hosts:
#    - raspi
#  postgresql: "12"
#  apt:
#    packages:
#      - postgresql-12
#      - postgresql-client-12
#
#before_script:
#  - psql -U postgres -d postgres -c "CREATE DATABASE finance_db;"
#  - psql -U postgres -d postgres -c "CREATE USER henninb WITH PASSWORD 'monday1';"
#  - psql -U postgres -d postgres -c "ALTER USER henninb CREATEDB;"
#  - psql -U postgres -d postgres -c 'ALTER USER henninb SUPERUSER;'
#  - psql -U postgres -d postgres -c 'GRANT ALL PRIVILEGES ON DATABASE finance_db TO henninb;'
#
#env:
#  global:
#    - PGPORT=5432
##    - PGUSER=henninb
#
#services:
#  - postgresql
#
#language: groovy
#jdk:
#  - openjdk11
#script: ./gradlew clean build
#
#notifications:
#  email: henninb@msn.com
#git:
#  autocrlf: input



addons:
  hosts:
    - raspi
  postgresql: "12"
  apt:
    update: true
    packages:
      - postgresql-12
      - postgresql-client-12

env:
  global:
    - PGPORT=5432
    - PGPASSWORD=monday1
    - PGUSER=henninb

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - psql --version
  - psql -p "${PGPORT}" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U henninb
  - psql -p "${PGPORT}" -c 'CREATE DATABASE finance_test_db;' -U henninb
  - psql -p "${PGPORT}" -c 'CREATE DATABASE finance_db;' -U henninb
  - psql -p "${PGPORT}" -c "CREATE USER henninb WITH PASSWORD 'monday1';" -U henninb
  - psql -p "${PGPORT}" -c 'ALTER USER henninb CREATEDB;' -U henninb
  - psql -p "${PGPORT}" -c 'ALTER USER henninb SUPERUSER;' -U henninb
  - psql -p "${PGPORT}" -c 'GRANT ALL PRIVILEGES ON DATABASE finance_test_db TO henninb' -U henninb
  - psql -p "${PGPORT}" -c 'GRANT ALL PRIVILEGES ON DATABASE finance_db TO henninb' -U henninb

after_script:
  - psql --version

services:
  - postgresql

language: java
jdk:
  - openjdk11

script: ./gradlew clean build

notifications:
  email: henninb@msn.com
git:
  autocrlf: input
